version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: hr_db
      MYSQL_USER: fast_api
      MYSQL_PASSWORD: fast_api_123
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hr-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: hr_db
      DB_USER: hr_user
      DB_PASSWORD: hr_123
    networks:
      - hr-network

volumes:
  db_data:

networks:
  hr-network:
    driver: bridge
